CREATE TABLE usNameData ( id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, sex TEXT NOT NULL, births INTEGER NOT NULL, rank INTEGER NOT NULL, year INTEGER NOT NULL );

CREATE TABLE nameMeanings ( id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, sex TEXT NOT NULL, nameData JSON );